spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: bazepodataka
        url: jdbc:postgresql://localhost:5432/Kompletici
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    servlet:
      multipart:
        max-file-size: 5MB
        max-request-size: 60MB

application:
    security:
        jwt:
            secret-key: 7iAGHtY6YttfJhHwAm6M5ZWidInVYZ+Una6I392a+sZdXfRNTiLebEFmagTx3u0b
            expiration: 86400000 # one day


logging:
    level:
        org:
            springframework: DEBUG
